# Generated by Django 5.0.1 on 2024-03-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_rename_orderid_orderdetail_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order_id',
            new_name='order',
        ),
    ]
