# Generated by Django 5.0.1 on 2024-03-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_rename_order_id_orderdetail_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.CharField(default='available', max_length=255),
        ),
    ]
