# Generated by Django 5.0.1 on 2024-03-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='DBImage/book_covers/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='DBImage/customer_images/'),
        ),
    ]
