# Generated by Django 5.0.1 on 2024-03-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='messagecontent',
            field=models.CharField(max_length=255),
        ),
    ]
