# Generated by Django 5.0.1 on 2024-04-03 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_order_payment_type_order_total_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='customer_id',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
